[profile.default]
solc-version = '0.8.22'
src = "src"
out = "out"
test = 'test'
cache_path = 'cache'
libs = ["lib"]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'forge-std/=lib/forge-std/src/',
    '@layerzerolabs/lz-evm-protocol-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-oapp-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp',
    '@layerzerolabs/lz-evm-messagelib-v2=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib',
    '@stargatefinance/stg-evm-v2=lib/stargate-v2/packages/stg-evm-v2',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils',
]

[rpc_endpoints]
optimismSepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
polygonAmoy = "${POLYGON_AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
optimismSepolia = { key = "${OP_ETHERSCAN_API_KEY}", url = "${OPTIMISM_SEPOLIA_ETHERSCAN_API}" }
arbitrumSepolia = { key = "${ARB_ETHERSCAN_API_KEY}" }
polygonAmoy = { key = "${POLYGONSCAN_API_KEY}" }